
name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Change this to your main branch if it's not 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Grant write access to repository contents
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Specify the Node.js version you need

      - name: Install dependencies
        run: |
          cd packages/frontend
          yarn install

      - name: Build
        run: |
          cd packages/frontend
          yarn build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: packages/frontend/build
