name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Default branch push triggers deployment

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: |
          cd packages/frontend
          yarn install

      - name: Build the project
        run: |
          cd packages/frontend
          yarn build

      - name: Upload static site artifacts
        uses: actions/upload-pages-artifact@v1
        with:
          path: packages/frontend/build  # Path to the build folder

  deploy:
    runs-on: ubuntu-latest
    needs: build  # Ensures deployment runs after the build step
    permissions:
      pages: write  # Allow pushing to GitHub Pages
      id-token: write  # Required for authentication
    environment:
      name: github-pages
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
